### ISSUE TITLE
Cloudflare turnstile issue.

### ISSUE THREAD

**Issue by Gait0fH3ll** [g1879/DrissionPage#39]
resolved

**Comment by HkerVit** [comment]
today i have same error. I canot click to checkbox cloudflare.
how to fix?

**Comment by g1879** [comment]
Send me the URL. I tested the code in the video and it works.
https://www.bilibili.com/video/BV1f24y1c7qG

**Comment by HkerVit** [comment]
Done. Tks sir fixed

**Comment by lihanchen** [comment]
I still can't pass cloudflare.
Tried the code from GaitOfH3ll and the code on Bilibili.
GaitOfH3ll worked until a few days ago.
Tested with https://nowsecure.nl and DrissionPage 3.2.31

**Comment by g1879** [comment]
> I still can't pass cloudflare. Tried the code from GaitOfH3ll and the code on Bilibili.
> 
> ```python
> def skip_cloudflare(driver: ChromiumPage):
>     iframe = driver.get_frame('@src^https://challenges.cloudflare.com/cdn-cgi')
>     if iframe:
>         iframe('.mark').click()
>     # while True:
>     #     try:
>     #         if driver('xpath://div/iframe').s_ele("xpath://input[@type='checkbox']") is not None:
>     #             print("click")
>     #             driver('xpath://div/iframe').ele("xpath://input[@type='checkbox']", timeout=0.1).click()
>     #         else:
>     #             print("done")
>     #             return
>     #     except:
>     #         time.sleep(.1)
> ```
> 
> GaitOfH3ll worked until a few days ago. Tested with https://nowsecure.nl and DrissionPage 3.2.31

watch here: https://youtu.be/TCRcRXszhhU

**Comment by Gait0fH3ll** [comment]
Great solution

**Comment by lizhen1412** [comment]
> Send me the URL. I tested the code in the video and it works. I tested the code in the video and it worked. https://www.bilibili.com/video/BV1f24y1c7qG

This video it's gone, bad.
